### PR TITLE
Add ThemeManager

### LINKED ISSUE #361: Simplify ResourceDictionary
In one of the controls, I saw that this is how they wrote their dictionaries
```
<Application
    ...
    xmlns:ui="http://schemas.modernwpf.com/2019">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

This is very good and simple, It would be great if the HandyControl also supported it something like this:
```
<hc:Controls/>
<hc:Theme Skin="Light"/>
```

### PR DESCRIPTION
**Pull request by ghost1372**
I implemented this PR with the help of [ModernWpf](https://github.com/Kinnara/ModernWpf) project

## What does this PR do?
- Add ThemeManager
- Add #500 

### HandyControl.csproj
- Theme.cs
- SkinType.cs
- SkinDefault.xaml
- SkinDark.xaml
- SkinViolet.xaml
- Brushes.xaml
- ColorsViolet.xaml

### HandyControlDemo.csproj
- DemoTheme.cs
- SkinDefault.xaml
- SkinDark.xaml
- Brushes.xaml
- Colors.xaml
- ColorsDark.xaml

## Things that have been renamed and moved:
- Colors.xaml reanamed to Light.xaml
- ColorsDark.xaml reanamed to Dark.xaml
- Brushes content moved to Light.xaml and Dark.xaml 

> **_NOTE:_**  SkinViolet.xaml and ColorsViolet.xaml completely Removed because we can add Violet and even more theme with the help of the ThemeManager and AccentColor Property

## What classes have been added?
All classes are added to a folder called ThemeManager, There is a folder in this class called Markup
These markup classes help us to bind brushes so that we can use the ThemeManager

> **_NOTE:_** In Brushes DynamicResource replaced with m:StaticColor: `<SolidColorBrush ... Color="{m:StaticColor LightPrimaryColor}" />`

## How to Address Resource?
```xml
<ResourceDictionary>
     <ResourceDictionary.MergedDictionaries>
           <hc:ThemeResources/>
           <hc:Theme/>
      </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

## Set the application theme
To override the default settings, set properties on the `ThemeResources` class in App.xaml. For example:

### Xaml
```xml
<hc:ThemeResources RequestedTheme="Dark" AccentColor="Red"/>
```

### Code-Behind
```cs
ThemeManager.Current.ApplicationTheme = ApplicationTheme.Dark;
ThemeManager.Current.AccentColor= Brushes.Red;
```

- If you want to specify the Accent Color for whole application in `Xaml (ThemeResources)`, you must use the `AccentColor` property.
- If you want to specify the Accent Color for whole application in `C# code`, you must use `ThemeManager` Class and `AccentColor` property.
- If you want to specify the Accent Color of the `FrameworkElements`, you must use `ThemeManager` Class and `ActualAccentColor` attached property.

|Name|NameSpace|Type|Remarks|
|-|-|-|-|
|AccentColor|ThemeResource|Brush|specify the Accent Color for whole application|
|AccentColor|ThemeManager|DependencyProperty|specify the Accent Color for whole application|
|ActualAccentColor|ThemeManager|AttachedProperty|specify the Accent Color for FrameworkElements|

## Override the theme at element level
Set the `ThemeManager.RequestedTheme` or `hc:ThemeManager.ActualAccentColor` attached property on any FrameworkElement. For example:

```xml
<Border Background="{DynamicResource RegionBrush}" Padding="12" hc:ThemeManager.RequestedTheme="Dark">
    <Button Content="Dark theme button" />
</Border>

<Border Background="{DynamicResource RegionBrush}" Padding="12" hc:ThemeManager.ActualAccentColor="Red">
    <CheckBox Content="Accent Color" />
</Border>
```
Now this Border and its descendants will use the dark theme while the theme used by the rest of the app remains unchanged. 

## Change Application Theme with System Theme Change
If `UsingSystemTheme` is enabled in `ThemeResources` (default is `false`), By changing the Windows theme (Light/Dark and Accent Color), the theme of the program also changes automatically.

For systems running Windows 10, the system accent color and system Theme is used. for windows 7 system accent color and the light theme is used.
For systems running an earlier version of Windows, the light theme and the color PrimaryBrush (default blue) are used.

```xml
<hc:ThemeResources UsingSystemTheme="true"/>
```

### SystemThemeChanged Event
There is also an event called `SystemThemeChanged` if you want to do more.

```xml
<hc:ThemeResources UsingSystemTheme="true" SystemThemeChanged="ThemeResources_OnSystemThemeChanged"/>
```

```cs
private void ThemeResources_OnSystemThemeChanged(object? sender, FunctionEventArgs<ThemeManager.SystemTheme> e)
{
    Debug.WriteLine(e.Info.AccentBrush);
    Debug.WriteLine(e.Info.CurrentTheme);
}
```

also if you want to use this event in another class you can use ThemeManager

```
ThemeManager.Current.SystemThemeChanged += OnSystemThemeChanged;
```

Themes

## Override predefined colors
You can overwrite predefined resources Note that you need to know the resource key to override it.
also you can change your colors and styles according to the theme of the program.

Edit the `hc:ThemeResources` element in `App.xaml` to following:
```xml
<hc:ThemeResources>
    <hc:ThemeResources.ThemeDictionaries>
        <ResourceDictionary x:Key="Light" hc:ThemeDictionary.Key="Light">
            <SolidColorBrush x:Key="PrimaryBrush" Color="Red" />
            <SolidColorBrush x:Key="AppBackgroundBrush" Color="#FFF1F1F1" />
            <SolidColorBrush x:Key="AppContentBackgroundBrush" Color="{StaticResource SystemAltHighColor}" />
            <SolidColorBrush x:Key="CustomThemeBrush" Color="Red" />
        </ResourceDictionary>

        <ResourceDictionary x:Key="Dark" hc:ThemeDictionary.Key="Dark">
            <SolidColorBrush x:Key="PrimaryBrush" Color="Green" />
            <SolidColorBrush x:Key="AppBackgroundBrush" Color="#FF232323" />
            <SolidColorBrush x:Key="AppContentBackgroundBrush" Color="#FF282828" />
            <SolidColorBrush x:Key="CustomThemeBrush" Color="Yellow" />
        </ResourceDictionary>
    </hc:ThemeResources.ThemeDictionaries>
</hc:ThemeResources>
```

### CODE REVIEW

**Comment by NaBian** [comment]
i have two questions:
1. why we need multiple themes at the same time, are there any practical examples?
2. does this pr support IntelliSense? for instance, ButtonPrimary.

**Comment by ghost1372** [comment]
1. I did not test but I think WinUI library has this feature. However, there may be a situation where we use different themes at the same time
2.Unfortunately not now, but can be solved with a design time file like this
```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/HandyControl;Component/Themes/Theme.xaml"/>
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

UPFATE:
i reported this issue to visual studio team
Don't worry about IntelliSense
We can use design time file inside the vsix and nuget package.

**Comment by NaBian** [comment]
1. multi themes at the same time is pretty cool, while it's too rare, i.e. expenses don't correspond to incomes.
2. don't commit suicide, we have other more interesting things waiting for us. 😆

**Comment by ghost1372** [comment]
> 1. multi themes at the same time is pretty cool, while it's too rare, i.e. expenses don't correspond to incomes.
> 2. don't commit suicide, we have other more interesting things waiting for us. 😆

I realized that this multi-theme feature is known as **`theme at element level`**
infragistics support it. (Application Level theme and Control level theme )😁
see [here](https://www.infragistics.com/products/wpf/styling-themes/theme-manager)

> It’s never been easier to apply themes to Infragistics controls. Change the theme of a single control or an entire application with a single line of code using the ThemeManager. 

I just think about improving handycontrol, that's all❤
I want to see more from handycontrol It's still too early to commit suicide😁😅

**Comment by ghost1372** [comment]
😫 According to Microsoft, this behavior of IntelliSense is normal

**Comment by GF-Huang** [comment]
Is this built-in [HandyControls](https://github.com/ghost1372/HandyControls) 3.0.0?

**Comment by ghost1372** [comment]
@GF-Huang  Not yet, but if this PR is rejected I will add immediately

**Comment by ghost1372** [comment]
@NaBian When do you want to check this PR? Could it be faster?

**Comment by GF-Huang** [comment]
@ghost1372 By the way, why not open the issue feature for [HandyControls](https://github.com/ghost1372/HandyControls)?

**Comment by GF-Huang** [comment]
> > @GF-Huang Not yet, but if this PR is rejected I will add immediately
> 
> Bumping this PR because it's been over a month.
> This PR will make our company decide if to use HC or not.

Agree, the decision makers are too slow.

Making the PRs as standalone nuget package will be better.

**Pull request closed without merging**
