### PR TITLE
Move Demo To Prism

### PR DESCRIPTION
**Pull request by ghost1372**
Hi @NaBian 
I have started the transfer (#506 )
There are some things that need to be clarified before I go any further
1.Prism is not supported on .NET 4.5 and 4.0 So I just created a .NET 5 based demo (Also, the demo content is the same in all frameworks, and I do not think there is a need to separate demos for frameworks.)
2.I had trouble using the T4 file (LangProvider) and received strange errors So I decided to delete it and use another alternative I found a way to do it and put its classes here ([https://github.com/ghost1372/HandyControl/tree/MoveToPrism/src/Shared/HandyControlDemo/Tools/Extension](https://github.com/ghost1372/HandyControl/tree/MoveToPrism/src/Shared/HandyControlDemo/Tools/Extension))
3.Everything looked great until I realized that the language change does not happen in the left menu And the program must be restarted to apply the changes in the left menu

If you do not have any problems with the above, I can continue the transfer
If you have a problem with the above, please add some commits for fixing problems so I can keep working

### CODE REVIEW

**Comment by NaBian** [comment]
ignore .net 4.0 is unfriendly to some users, a compromise is that a prism demo can be created independently, at last we will have HandyControlDemo.Mvvmlight, HandyControlDemo.Prism  and so on. in prism demo, we can use the latest .net.

**Comment by ghost1372** [comment]
@NaBian  What do you think about 2 and 3?

> 2.I had trouble using the T4 file (LangProvider) and received strange errors So I decided to delete it and use another alternative I found a way to do it and put its classes here (https://github.com/ghost1372/HandyControl/tree/MoveToPrism/src/Shared/HandyControlDemo/Tools/Extension)
> 3.Everything looked great until I realized that the language change does not happen in the left menu And the program must be restarted to apply the changes in the left menu

**Comment by NaBian** [comment]
for simplicity, we can focus on usage rather than internationalization

**Comment by ghost1372** [comment]
> for simplicity, we can focus on usage rather than internationalization

So you mean to remove multiple languages and use only English?
I agree

**Comment by NaBian** [comment]
> > for simplicity, we can focus on usage rather than internationalization
> 
> So you mean to remove multiple languages and use only English?
> I agree

🤝

**Comment by ghost1372** [comment]
Due to the above conversations, I will close this request and create a new one when the job is done.

**Pull request closed without merging**
