### PR TITLE
Update BlurWindow.cs

### PR DESCRIPTION
**Pull request by ghost1372**
if Transparency effect is disabled in Windows Settings lag does not happen

### CODE REVIEW

**Comment by NaBian** [comment]
Huh? why did you close the issue?

**Comment by ghost1372** [comment]
> Huh? why did you close the issue?

Acrylic is no longer used on most surfaces in Windows 11
https://github.com/riverar/sample-win32-acrylicblur/issues/2#issuecomment-873612950

And we can use better way (disabling acrylic when resizing or moving window)
https://github.com/sourcechord/FluentWPF/issues/42#issuecomment-873615119

**Comment by NaBian** [comment]
Microsoft always likes to toss and turn 😞

**Comment by ghost1372** [comment]
@NaBian yes but look at here, [mica ](https://docs.microsoft.com/en-us/windows/apps/design/style/mica) is beautiful 😁
Maybe it's time for HandyControl to redesign visuals accourding to mica materials

image
image
image

**Pull request closed without merging**
