### PR TITLE
set borderThickness to 1

### PR DESCRIPTION
**Pull request by ghost1372**
The default borderThickness has a black thickness of 20 and does not create an interesting look so i changed default value from 20 to 1

### CODE REVIEW

**Comment by NaBian** [comment]
if you change default value from 20 to 1, when you use the showdialog method to display information, the shadow of popwindow will disappear.

**Comment by ghost1372** [comment]
Ok, I wanted to solve this Black Border problem do you Have a solution?
untitled

**Comment by NaBian** [comment]
you can set PopWindow.AllowsTransparency to true

**Comment by ghost1372** [comment]
tnx fixed ;)

**Pull request closed without merging**
