### PR TITLE
add SimpleStackPanel

### PR DESCRIPTION
**Pull request by ghost1372**
auto spacing items
Untitled

### CODE REVIEW

**Comment by NaBian** [comment]
you have extended stackpanel, while the name of the new control is simplestackpanel, It's not simple! we might need a better name.

**Comment by NaBian** [comment]
And we'd better not copy the code directly from other projects, we need to have our own originality

**Comment by ghost1372** [comment]
@NaBian  ok
how about hc:StackPanel?
Yes, copying without checking is not good, But I try to find good features and add to this project. I always read the code I copy.

**Comment by NaBian** [comment]
actually we can use flexpanel
```
<hc:FlexPanel JustifyContent="SpaceBetween" VerticalAlignment="Top">
    <Border Width="30" Height="30" Background="Black"/>
    <Border Width="30" Height="30" Background="Black"/>
    <Border Width="30" Height="30" Background="Black"/>
    <Border Width="30" Height="30" Background="Black"/>
</hc:FlexPanel>
```

**Comment by ghost1372** [comment]
@NaBian  yes but behavior is different 😶
i renamed SimpleStackPanel to StackPanel
Untitled

**Comment by NaBian** [comment]
SimpleStackPanel is still very useful(e.g. performance optimization), if spacing property is removed. at the same time, we also need spacing, we can add a new panel called UniformSpacingPanel, is has three props: Orientation, ChidWrapping, Spacing, what do you think? @ghost1372

**Comment by ghost1372** [comment]
> SimpleStackPanel is still very useful(e.g. performance optimization), if spacing property is removed. at the same time, we also need spacing, we can add a new panel called UniformSpacingPanel, is has three props: Orientation, ChidWrapping, Spacing, what do you think? @ghost1372

It looks good
I agree

**Comment by NaBian** [comment]
close in #611

**Pull request closed without merging**
