### PR TITLE
Add japanese language support

### PR DESCRIPTION
**Pull request by musashi-miyamoto**
This adds the japanese language translation support.

## Changes

- Adds japanese string resources (.resx)
- Adds flag image
- Adds japanese flag button to the demo app

## Testing

I checked these controls.

- [x] MessageBox button text
- [x] ColorPicker button text
- [x] TimeBar interval text
- [x] Pagination jump button text
- [x] Clock AM/PM

MessageBox
ColorPicker
TimeBar
Pagination
Clock

### CODE REVIEW

**Comment by NaBian** [comment]
awesome work! can you provide language for hc demo too? 😄

**Comment by ghost1372** [comment]
> awesome work! can you provide language for hc demo too? 😄

hmm... already done!
Untitled

**Comment by NaBian** [comment]
> > awesome work! can you provide language for hc demo too? 😄
> 
> hmm... already done! Untitled

no, all in english.

**Comment by musashi-miyamoto** [comment]
> > > awesome work! can you provide language for hc demo too? 😄
> > 
> > 
> > hmm... already done! Untitled
> 
> no, all in english.

ok now I'm working on it, please wait a still :runner:

**Comment by musashi-miyamoto** [comment]
Demo-app translation done!

**Pull request merged**
