### PR TITLE
Fix TabControl behavior

### PR DESCRIPTION
**Pull request by codingdna2**
This PR fix the behaviors as described in issue #357 .

- [x] Button overflow is shown when Tabs space is full
- [x] Selection of a tab outside the visible area move the scrollbar
- [x] New tab when the tab area is full, should move the scrollbar
- [x] During resize, the active tab should be kept visible

It's a bit different with respect to VS behavior:

Visual Studio switch the order inside the context menu but not the order of the tabs. In fact the context menu is bound to the **navigation order** while the UI only keep the position. As HandyControl doesn't handle the navigation order, I guess the correct behavior is the suggested one. This feature (navigation order) can be a future enhancement.

### CODE REVIEW

**Comment by NaBian** [comment]
add the following code will throw an error
image

**Comment by codingdna2** [comment]
Sorry, my bad I didn't checked the combination. It's now fixed! 

It's worth noting that the TabControlPlusTemplate is quite limited. I left it untouched but with the addition of scrollviewer points 2, 3, 4 would work.

**Comment by NaBian** [comment]
i delete some tabitems until overflowbutton disappear, the right border thickness will be 2px not 1px.
4SPDMH86S%OL T`01)W9EVT

i will remove some of the features you added to avoid this problem or do you have a better way?

**Comment by codingdna2** [comment]
If I understand well, the border on line 147 is required just to separate RepeatButton and ContextMenuToggleButton. If both are visible it should be visible otherwise it should be collapsed. Am I missing something?

EDIT: Just pushed a Multitrigger to implement the above.

**Comment by codingdna2** [comment]
Any feedback on this?

**Comment by ghost1372** [comment]
@codingdna2  be patient😄

**Comment by NaBian** [comment]
because new codes bring a new problem again, if we close a tabitem, the overflow button will disapear, move a tabitem, the overflow button will show.

too much logic makes the code more complex, so more tests are needed, more time too.

**Comment by codingdna2** [comment]
Never meant to be rude or impatient, just trying to be of help. I guess if I can reproduce the issue, I'll be working on myself (especially now that in Italy is lockdown period).

EDIT: I just found a way to reproduce it, I'll try to fix this one too. And sorry I didn't see it myself.

**Comment by codingdna2** [comment]
There are other issues, probably not related with my PR. I'm not sure I can fix it myself.

1. If you change select a semi-visible tab, it's not always made visible:
ItemOffsetX

2. If you resize from left, the tabs are flickering (image seems much better than reality):
ResizeFromLeft

**Pull request closed without merging**
