### PR TITLE
Add ExtendViewIntoNonClientArea

### PR DESCRIPTION
**Pull request by ghost1372**
https://github.com/HandyOrg/HandyControl/discussions/703

image

### CODE REVIEW

**Comment by GF-Huang** [comment]
Great, could you merge into `HandyControls` and push a preview/alpha version to nuget?

**Comment by ghost1372** [comment]
@GF-Huang I'm a little busy Maybe on the weekend

**Comment by GF-Huang** [comment]
https://github.com/HandyOrg/HandyControl/blob/112f26b4da8ac922daa9e4f793a74292824bd44d/src/Shared/HandyControl_Shared/Themes/Styles/Window.xaml#L169

This will make the `hc:Window.NonClientAreaContent` invisible. Collapse it maybe not a good idea if I want to set a few menu/button beside the system minimize button.

image

Even if I don't need the `NonClientAreaContent` (make ContentPresenterMain collapsed), the first side menu can only click the half bottom area.

2QmsiBEZ6K

Maybe a standalone control template that change the window layout struct will be better.

**Comment by ghost1372** [comment]
Because of
https://github.com/HandyOrg/HandyControl/blob/112f26b4da8ac922daa9e4f793a74292824bd44d/src/Shared/HandyControl_Shared/Themes/Styles/Window.xaml#L171

and

https://github.com/HandyOrg/HandyControl/blob/112f26b4da8ac922daa9e4f793a74292824bd44d/src/Shared/HandyControl_Shared/Themes/Styles/Window.xaml#L81

Items that are exactly on NonClientArea cause this problem (`Pane.ZIndex` causes NonClientArea to be placed on other controls, and if this feature is not set, Max, Min, Close buttons, etc. will be out of range.)

The solution could be to set margin for sidemenu

**Comment by ghost1372** [comment]
finally
https://github.com/HandyOrg/HandyControl/commit/0021d649f081d819b598073672e3833519fd4a35

**Pull request closed without merging**
