### PR TITLE
add drag property for windows

### PR DESCRIPTION
**Pull request by ghost1372**
now we can move windows with drag & drop (for some situations that we need windowsStyle="None" but movable windows)

### CODE REVIEW

**Comment by NaBian** [comment]
@ghost1372 tnx, you added dragwindows, but why didn't you add it to project ❓

**Comment by ghost1372** [comment]
@nabian demo project? I will add

**Comment by ghost1372** [comment]
@NaBian  i added demo

**Comment by NaBian** [comment]
image
It's weird, there's no demo here. I'll turn this pr off first. Can you submit it again?

**Comment by ghost1372** [comment]
@NaBian  ok i submit it again w8 a Minute

**Pull request closed without merging**
