### PR TITLE
Add Mica Support for Window

### PR DESCRIPTION
**Pull request by ghost1372**
Finally I was able to activate Mica for HC Windows 😁
I added mica to the [unofficial version](https://github.com/ghost1372/HandyControls/commit/31819e0f9d8acbff79f760e3c3f4bfdf8b5269f4)
Therefore, if people are waiting for this feature, they can use the unofficial version until this PR is merge

Mica

### CODE REVIEW

**Comment by Symbai** [comment]
//Edit: After some modifications I got it to work. However there is a problem since you get IsDarkMode from Windows settings. If Windows is light but my app is using the DarkTheme of HandyControl the Mica effect is light when it should be dark.

On addition to that I would like the Mica effect also apply on other controls. For example a button. Setting background brush to transparent works but makes the button not clickable.

It also doesn't work on `Window` with `ResizeMode="NoResize"`.

**Comment by ghost1372** [comment]
Hi @Symbai , according to microsoft

> Mica is an opaque, dynamic material that incorporates theme and desktop wallpaper to paint the background of long-lived windows such as apps and settings. 

so I think we should consider the Windows theme instead of app theme, however you can enable and disable mica with WindowHelper.cs class

https://github.com/HandyOrg/HandyControl/blob/83fec811aa08ded246a1de4cf61927285385ea74/src/Shared/HandyControl_Shared/Tools/Helper/WindowHelper.cs#L199

You should know that mica is designed for WinUI and has restrictions on WPF (We are currently doing this with undocumented p/invoke APIs)

**Comment by Symbai** [comment]
> so I think we should consider the Windows theme instead of app theme

On WinUI the whole app is based on the Windows Settings. On WPF the whole app is based on the theme you define yourself. So I don't think you should follow the docs for WinUI. Just my two cents, I will use the helper method.

Any idea why it doesn't work on `NoResize` mode? For consistency I would like to use it on every window but some of them should not be resizable.

**Comment by Symbai** [comment]
I figured out its because Mica completely renders the title bar including the minimize / maximize buttons. Maybe there is an undocumented API for Mica NoResize mode. I can see that Edge for example has Mica effect on all menus and context menus and they don't have system buttons so it might be possible.

**Comment by ghost1372** [comment]
hmmm.... i used **DetermineIfInLightThemeMode** method 
https://github.com/HandyOrg/HandyControl/blob/83fec811aa08ded246a1de4cf61927285385ea74/src/Shared/HandyControl_Shared/Controls/Window/Window.cs#L542

Which detects the current Windows theme through the Windows registry so i follow windows theme not app theme!
You should note that Mica was developed for WinUI and has restrictions on WPF (We activate mica with the help of undocumented p/invoke)
i dont know about NoResize mode but mybe related to

https://github.com/HandyOrg/HandyControl/blob/83fec811aa08ded246a1de4cf61927285385ea74/src/Shared/HandyControl_Shared/Tools/Helper/WindowHelper.cs#L201

**Comment by Symbai** [comment]
Note for the documentation:

In XAML if you set a background brush for the window and the line is AFTER `ApplyBackdropMaterial="true"`, in Windows 11 the Mica effect is applied to the Window but immediately overridden by the background brush, Mica effect goes away. Interestingly if you call `EnableMicaEffect` in code on this Window the effect doesn't come back.

Some XAML formatter extensions will sort the properties alphabetically. `ApplyBackdropMaterial` is then before `Background` and the "bug" above occurs. This is useful to know for devs trying to figure out why Mica doesn't show up. But also for authors when dealing with issue tickets.

**Comment by ghost1372** [comment]
@Symbai  i updated [docs](https://hosseini.ninja/handycontrol/extend_controls/window/#Mica-Material) tnx

**Comment by Symbai** [comment]
@ghost1372 This (Mica) seems to no longer work in latest Windows 11 Insider. According to [this person](https://github.com/lepoco/wpfui/issues/5) Microsoft has disabled this trick. Which i can confirm using a virtual machine machine.

**Comment by dongle-the-gadget** [comment]
In 22523 there's a DWM API for Mica, however we need to use different parameters for `DwmSetWindowAttribute`.
```
int param = 2;
DwmSetWindowAttribute(new WindowInteropHelper(this).Handle, 38, ref param, Marshal.SizeOf<int>());
```

**Comment by ghost1372** [comment]
I am closing this pr due to its issues.
I will create a new pr soon with fixed issues.

**Pull request closed without merging**
