### PR TITLE
Add to VSIX - Fix Intellisense Resources identifiable

### PR DESCRIPTION
**Pull request by ghost1372**
From now on, those using vsix can view all Resources by IntelliSense
Unfortunately I was unable to add this feature to HandyControlDemo project. SharedProjects are a bit confusing to me.
Untitled

### CODE REVIEW

**Comment by NaBian** [comment]
I don't think it's hc's problem. You see,it's normal here:
demo

**Comment by ghost1372** [comment]
@NaBian  wow, Which version of Visual Studio do you use?
yes, this is not an hc`s problem and it is related to Visual Studio Designer

**Comment by NaBian** [comment]
16.3.7

**Comment by ghost1372** [comment]
It's a little weird
I used official versions before, and this problem persisted
I have been using the preview version for the last 6 months (now is 16.4 prev 3)
Has Intellisence worked for you before? Or is it working recently?
Excuse me for all this

**Comment by NaBian** [comment]
I think it's always been useful.

**Pull request closed without merging**
